### ISSUE TITLE
Form submit when action is a relative path

### ISSUE THREAD

**Issue by BlaXpirit** [hickford/MechanicalSoup#10]
*http://example.com/test/form.html*
```html
<form action="some_relative_path"
```

```python
browser.submit(my_form)
```

    requests.exceptions.MissingSchema: Invalid URL u'some_relative_path': No schema supplied. Perhaps you meant http://some_relative_path?

Please allow submitting forms fully automatically, resolving the relative *action* path. This should be resolved to *http://example.com/test/some_relative_path*

**Comment by BlaXpirit** [comment]
Oh this isn't so bad with [`urlparse.urljoin`](https://docs.python.org/library/urlparse.html#urlparse.urljoin)

```python
browser.submit(urlparse.urljoin(my_page.url, my_form['action']))
```

**Comment by hickford** [comment]
Hi Oleh. Thanks for your message. Let me take a look.

Ah I remember this. The challenge is the form object doesn't know the url it came from. As a convenience I added a second parameter to `browser.submit` to be used to resolve action:
    
    page = browser.get(url)
    form = page.soup.select('form')[0]
    browser.submit(form, page.url)

Example https://github.com/hickford/MechanicalSoup/blob/9df83dc607dad5d72bf0fb3c432d34253c43828a/example.py#L24

This deserves a mention in the docs.

**Comment by BlaXpirit** [comment]
`page.url` is not good, because action URL is different.

**Comment by hickford** [comment]
Pardon that wasn't clear, it does a urljoin on page.url and action. Check the code https://github.com/hickford/MechanicalSoup/blob/9df83dc607dad5d72bf0fb3c432d34253c43828a/mechanicalsoup/browser.py#L30

**Comment by BlaXpirit** [comment]
Indeed it works exactly the same. Thanks and sorry.
