### ISSUE TITLE
Very minor issue with method placement

### ISSUE THREAD

**Issue by RedSpiderMkV** [hickford/MechanicalSoup#14]
Hey, nice work.
Tiny non-issue really, in mechanicalsoup/browser.py
Line 88

Method: submit

That's a public method?  Should it be placed with the other public methods above the private methods,  _build_request and _prepare_request?  I'm assuming those are 'private' methods anyway.

Anyway, this looks pretty great.  Thanks!

**Comment by hickford** [comment]
Hello from Lilliput! It doesn't bother me. Glad the library is useful to you, thanks for the compliment.
