### ISSUE TITLE
allow customization of BeautifulSoup instance

### ISSUE THREAD

**Issue by simon-weber** [hickford/MechanicalSoup#15]
BeautifulSoup is initialized inside add_soup, so there's no way for clients to, for example, specify a different parser.

Some ways this could be done:
* accept a dict of kwargs to provide to the constructor. It looks like their init doesn't take *args, so this should cover everything.
* accept a factory to delegate instance construction to client code

**Comment by hickford** [comment]
Hi Simon. Good idea, let me take a look

https://github.com/hickford/MechanicalSoup/blob/master/mechanicalsoup/browser.py#L14

**Comment by hickford** [comment]
Are any of the other options important, or would simply adding a parser argument suffice?

http://www.crummy.com/software/BeautifulSoup/bs4/doc/#making-the-soup

**Comment by simon-weber** [comment]
Thanks! I like the choice to provide arbitrary config.

I left a quick note on that commit.
