### ISSUE TITLE
Compare with RoboBrowser

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [hickford/MechanicalSoup#20]
What kind of comparison with RoboBrowser?

**Comment by wernight** [comment]
This project seems more active but I didn't find the equivalent for clicking links:

    # Look up my favorite song
    song_link = browser.get_link('trains')
    browser.follow_link(song_link)

**Comment by moy** [comment]
We now have `follow_link` and related features in [stateful_browser.py](https://github.com/hickford/MechanicalSoup/blob/master/mechanicalsoup/stateful_browser.py), so both projects now seem more or less equivalent in terms of features.

RoboBrowser has more lines of codes (see [openhub comparison](https://www.openhub.net/p/_compare?project_0=MechanicalSoup&project_1=RoboBrowser) for example), but I see the small number of lines of code in MechanicalSoup as one of its features: it makes it easy to hack. Real features are in requests and BeautifulSoup.

**Comment by moy** [comment]
I think my previous comment answered the initial question, but feel free to open issues for more specific questions if needed.
