### ISSUE TITLE
No parser was explicitly specified

### ISSUE THREAD

**Issue by stdex** [hickford/MechanicalSoup#22]
/usr/local/lib/python3.4/dist-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

Need to use add_soup method or what?

**Comment by stdex** [comment]
Need to use:
`browser = mechanicalsoup.Browser(parser='html.parser')`
or
`browser = mechanicalsoup.Browser(parser='lxml')`

**Comment by hickford** [comment]
Ah presumably the warning was added by a recent version of BeautifulSoup. It's not obvious what parser MechanicalSoup should default to. Your workaround looks good to me.

**Comment by lawli3t** [comment]
when i try to use
```
        browser = mechanicalsoup.Browser(parser = "lxml")
```

i get the following error message:
```
TypeError: __init__() got an unexpected keyword argument 'parser'
```

I also cant find the keyword parser in the constructor for the mechanicalsoup browser, so why would this work?

**Comment by hickford** [comment]
@lawli3t maybe you're using an old version. Try simply `mechanicalsoup.Browser()`

**Comment by gsora** [comment]
Error is still present, from both ArchLinux's packaged version and pip3 version.

**Comment by hickford** [comment]
You're right. Let me take a look.

**Comment by wernersa** [comment]
The easy fix for this is to use the parameter soup_config:
mechanicalsoup.Browser(soup_config={"features":"lxml"})

**Comment by EvilMav** [comment]
wernersa's solution works for me (while stdex'es fails with a TypeError). I'd expect html.parser to be used by default and/or a more obvious parameter to specify the expected parser.

**Comment by hsiaoyi0504** [comment]
It's just because the `__init__()` in
[browser.py](https://github.com/hickford/MechanicalSoup/blob/master/mechanicalsoup/browser.py)
doesn't have the `parser` argument. Instead, there is a argument `soup_config` should be settled up.

By the way, seems the 'lxml' are not supported in recently change [check this issue](https://github.com/hickford/MechanicalSoup/pull/34)

I think this issue can be closed.

**Comment by fmj02** [comment]
Got the same issue even after setting:
`soup_config={'features': 'html.parser'}`

**Comment by hugovk** [comment]
It'd also be good to default to a sensible value.

**Comment by hickford** [comment]
Voila! https://pypi.python.org/pypi/MechanicalSoup/0.5.0

Sorry for the lack of attention to this project—I'm getting married next year =)
