### ISSUE TITLE
Uh, can it be as mechanize as use cookiejar?

### ISSUE THREAD

**Issue by GroverChouT** [hickford/MechanicalSoup#24]
Like this:

    browser = mechanize.Browser()
    browser.set_cookiejar(cookiejar)
    browser.open('')

**Comment by hickford** [comment]
What's cookiejar?

**Comment by GroverChouT** [comment]
Um... We use it to save cookies, here: http://wwwsearch.sourceforge.net/mechanize/doc.html#supplying-a-cookiejar

**Comment by GroverChouT** [comment]
Because Mechanical does not support Python3 and not have a good enough substitute, (reluctantly) So I still go with Python 2.

**Comment by hickford** [comment]
I don't understand the problem. Can you explain clearly?
