### ISSUE TITLE
multi-value select input not supported for .submit()

### ISSUE THREAD

**Issue by Jajcus** [hickford/MechanicalSoup#26]
.submit() won't work for mult-value `<select>` input – always only the last selected value is used.

**Comment by hickford** [comment]
Like this? http://www.w3schools.com/tags/att_select_multiple.asp

    <select multiple>
      <option value="volvo">Volvo</option>
      <option value="saab">Saab</option>
      <option value="opel">Opel</option>
      <option value="audi">Audi</option>
    </select>

**Comment by Jajcus** [comment]
Yes, like this. I have already prepared a fix, will make a pull request in a moment.
