### ISSUE TITLE
Wrong value sent for enabled checkbox or radio input with no value

### ISSUE THREAD

**Issue by Jajcus** [hickford/MechanicalSoup#27]
MechanicalSoup always sends empty value for `<input>` elements with no value defined. That doesn't work well for radio and checkbox inputs – real browser would use "on" in such case. Empty value used by MechanicalSoup does not work for Django forms.

**Comment by hickford** [comment]
Can you give an example in HTML?

**Comment by Jajcus** [comment]
From a Django-generated user change form:
```
<input checked="checked" id="id_is_active" name="is_active" type="checkbox" /><label class="vCheckboxLabel" for="id_is_active">Active</label>
<p class="help">Designates whether this user should be treated as active. Unselect this instead of deleting accounts.</p>
```

When this form is submitted with `is_active=` (like MechanicalSoup currently does), Django would handle it like the checkbox is not checked and the user would be deactivated. Firefox sends `is_active=on` in this case.  This is probably a Django bug (HTML spec says 'value' is required here), but MS should behave like normal browsers.

I have a patch ready, a will make a pull request soon.
