### ISSUE TITLE
Elements without closing tags not appearing in the soup

### ISSUE THREAD

**Issue by scarrick68** [hickford/MechanicalSoup#32]
None of the self closing tag elements appear in the soup. I saw a post on SO saying that using 'lxml' as my parser would fix it, but that's not working. I get the error message saying no parser was specified so it's defaulting to lxml on my system, but I still don't see any span, a or meta tags.

**Comment by hickford** [comment]
lxml is the best parser to use. Try `mechanicalsoup.Browser(soup_config=dict(features='lxml'))`

You'll need to install it from PyPI http://lxml.de/installation.html

See also https://www.crummy.com/software/BeautifulSoup/bs4/doc/#differences-between-parsers
