### ISSUE TITLE
Can not login to a site

### ISSUE THREAD

**Issue by lben** [hickford/MechanicalSoup#33]
I am trying to login to https://peerfly.com/login.php but after the submit call I am stuck in the same login page. The mechanize version works fine but I want to make it work with MechanicalSoup is there any problem or am I missing something?

This is the code that I am using:

```
import mechanicalsoup

browser = mechanicalsoup.Browser(soup_config={'features':'html.parser'})
loginPage = browser.get('https://peerfly.com/login.php')
form = loginPage.soup.find_all('form')[0]
form.find('input', {'name':'email'})['value'] = 'myuser'
form.find('input', {'name':'password'})['value'] = 'mypassword'
page = browser.submit(form, loginPage.url)
print page.text
```

Thank you

**Comment by hickford** [comment]
Did you figure it out?

**Comment by moy** [comment]
This is an old bug and given the absence of reply to the last comment, I'm assuming it's no longer valid.

@lben: feel free to re-open if you're still encountering the bug with the latest version.
