### ISSUE TITLE
cookiejar file

### ISSUE THREAD

**Issue by mghadam** [hickford/MechanicalSoup#37]
Is it possible to set a cookiejar file so that the sessions could be saved and used several times?

**Comment by andpozo** [comment]
@mghadam:

MechanicalSoup is a wrapper for python requests and uses a Session class for browser session.

from http://docs.python-requests.org/en/master/api/#requests.Session.cookies:

> A CookieJar containing all currently outstanding cookies set on this session. By default it is a RequestsCookieJar, but may be any other cookielib.CookieJar compatible object.

and from http://docs.python-requests.org/en/master/api/#requests.cookies.RequestsCookieJar 

> Compatibility class; is a cookielib.CookieJar, but exposes a dict interface.

so... I assume that the MechanicalSoup uses a CookieJar if not you can initialize your Browser with a custom session:

``` python
import requests
import mechanicalsoup
from http import cookiejar

c = cookiejar.CookieJar() #you can chooise another cookie store like a LWPCookieJar
s = requests.Session()
s.cookies = c
browser = mechanicalsoup.Browser(session=s)
```

**Comment by hickford** [comment]
Right. mechanicalsoup.Browser wraps requests.Session, so it automatically stores cookies for the lifetime of the Browser object.

If you wish to save cookies between executions of your app, you can pickle the Browser object (or the session, or the cookie jar). See https://docs.python.org/3/library/pickle.html 

Perhaps this deserves some documentation in the readme

**Comment by scotbond** [comment]
Dumping StatefulBrowser with pickle may produce error "RecursionError: maximum recursion depth exceeded".

I found this more appropriate:
```
# Save cookieJar from active session
pickle.dump(browser.get_cookiejar(), open("cookiejar.dump", 'wb'))
```
```
# Load cookiejar into fresh browser
cookiejar = pickle.load(open("cookiejar.dump", 'rb'))
browser.set_cookiejar(cookieJar)

```
