### ISSUE TITLE
how to change the headers?

### ISSUE THREAD

**Issue by yongseung** [hickford/MechanicalSoup#38]
I have tried a lot of ways...

like as
browser = mechanicalsoup.Browser()
browser.addheaders(...)

but actually, when I send a packet, there isn't header that I added
it's the same result when I look for packets with wireshark there isn't extra header

and also when I check with browser.session.headeres, it's the same result 
it bring the basic headers. 

Finally, I look up the all the member function in the browser class, I couldn't find it with your source
so is there a way to add a extra header??

it's impossible to get connection major portal where it require some cookies or extra headers.
is there a solution?

**Comment by hickford** [comment]
Try `browser.session.headers.update` as in the example at http://docs.python-requests.org/en/master/user/advanced/#session-objects

**Comment by yongseung** [comment]
Thank you it work's! I coudln't imagine that update function will add a header...
