### ISSUE TITLE
example.py seems broken

### ISSUE THREAD

**Issue by moy** [hickford/MechanicalSoup#40]
```
$ python example.py login password
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    login_form = login_page.soup.select_one('#login form')
TypeError: 'NoneType' object is not callable
```

I tried adding `print(login_page.soup.select_one)` before the guilty line and it is indeed `None`.

**Comment by moy** [comment]
I could get it to work with the following patch:

```
--- a/example.py
+++ b/example.py
@@ -15,7 +15,7 @@ login_page.raise_for_status()  # similar to assert login_page.ok but with full s
 
 # login_page.soup is a BeautifulSoup object http://www.crummy.com/software/BeautifulSoup/bs4/doc/#beautifulsoup 
 # we grab the login form
-login_form = login_page.soup.select_one('#login form')
+login_form = mechanicalsoup.Form(login_page.soup.select('#login form')[0])
 
 # specify username and password
 login_form.input({"login": args.username, "password": args.password})
```

But I'm not convinced it's the right way. I don't understand why the `select_one` field exists but is `None`? Also, what I did is actually reverting 4d89436bce6817b81e9ee76495bb8e4650dbb97a ... Any idea?

Thanks,

**Comment by moy** [comment]
Just a ping on this one as I'm seeing some activity ...

Does `example.py` work as-is for other people? If my fix seems correct, I'll resubmit as a pull-request.

**Comment by gwynnebaer** [comment]
I can confirm that the patch above worked for me. @moy

**Comment by moy** [comment]
Thanks, @gwynnebaer. Actually, I'm not having the "'NoneType' object is not callable" anymore, it was probably an issue with a version of beautifulsoup. So, the `select_one` is not an issue anymore, but creating a `mechanicalsoup.Form` is still needed. I understood the issue, see PR #50 for details.
