### ISSUE TITLE
how to handle javascript 

### ISSUE THREAD

**Issue by supyoung** [hickford/MechanicalSoup#46]
It is amazing to write elegant code with MechanicalSoup. But I wonder how to handle javascipt with MechanicalSoup? If I use selenium, it will become annoying complicated. Hope for your help.

**Comment by hickford** [comment]
Thanks. Alas if you really need Javascript, there's no alternative to use a browser or something like Selenium http://www.seleniumhq.org/

In the case the Javascript does something very simple, like complete a form, you can try to follow it in a browser inspector and implement the same steps yourself.

**Comment by supyoung** [comment]
Well, I suppose there is no other choice.
