### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'features'

### ISSUE THREAD

**Issue by krsyoung** [hickford/MechanicalSoup#47]
The following line of code seems to be causing problems:

```
self.browser = mechanicalsoup.Browser(soup_config={'features':'html.parser'})
```

This will consistently result in the following error:

```
  File "/usr/local/lib/python2.7/dist-packages/mechanicalsoup/browser.py", line 32, in get
    Browser.add_soup(response, self.soup_config)
  File "/usr/local/lib/python2.7/dist-packages/mechanicalsoup/browser.py", line 23, in add_soup
    response.content, "html.parser", **soup_config)
TypeError: __init__() got multiple values for keyword argument 'features'
```

Here are the versions I'm using in `pip`:

```
beautifulsoup4==4.5.1
mechanicalsoup==0.5.0
```

I'm actually trying to debug a different issue (I think the html.parser is having some issues with some funky content so I was trying to change to lxml when this happened).

Thanks for any ideas!

**Comment by krsyoung** [comment]
In look at the code seems like it is due to this change:  https://github.com/hickford/MechanicalSoup/commit/3d3019e9f06bee860beeaffa505d97af3735a1ab

I guess removing the warning causes it to have a fit when explicitly trying to specify the HTML parser.

**Comment by hickford** [comment]
Thanks. Let me take a look

**Comment by hickford** [comment]
You're right.

Fixed by https://github.com/hickford/MechanicalSoup/commit/014b00c9069c997b76d91968bb37ccdd764aa1b3

**Comment by krsyoung** [comment]
Thanks @hickford!
