### ISSUE TITLE
Extract cookies from session?

### ISSUE THREAD

**Issue by JohnTendik** [hickford/MechanicalSoup#52]
Hey, 

I was just wondering if there was a way to extract the session cookies from the page/browser to be used in other request calls outside of mechanical soup? 

I'm trying to do page.cookies.get_dict() but its returning empty. 

Thanks

**Comment by hickford** [comment]
Hi John. Yes you can. The requests Session object is accessible at `Browser().session`. You can pickle it for reuse. I believe you can also get a cookie jar object compatible with other Python libraries

http://docs.python-requests.org/en/master/user/advanced/#session-objects

http://docs.python-requests.org/en/master/api/#request-sessions

**Comment by JohnTendik** [comment]
Ahh brilliant, I guess my methodology was wrong, I had to use Browser().session when I was using page.cookies :D 

Thanks for the super quick response!
