### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by Kybernetisch** [hickford/MechanicalSoup#55]
Are proxies currently supported?

**Comment by moy** [comment]
Never tried, but MechanicalSoup uses Requests for all HTTP accesses, and Requests does support proxies: http://docs.python-requests.org/en/master/user/advanced/#proxies

Setting `$HTTP_PROXY` or passing `proxies=` to [`browser.get()`](https://github.com/hickford/MechanicalSoup/blob/master/mechanicalsoup/browser.py#L38) should work. If not, it should be easy to fix.

**Comment by moy** [comment]
Hi,

I think I answered your question so I'm closing the issue. Feel free to reopen if the solution I suggested doesn't work.
