### ISSUE TITLE
AttributeError: 'module' object has no attribute 'StatefulBrowser'   

### ISSUE THREAD

**Issue by r0fls** [hickford/MechanicalSoup#59]
Using the example from the readme I get the above error.

**Comment by moy** [comment]
You need the latest version (from git, not the latest released version yet) for this to work. Otherwise, you can also use [example_manual.py](https://github.com/hickford/MechanicalSoup/blob/master/example_manual.py) which works with older releases (but requires a bit more code to write).

**Comment by r0fls** [comment]
thank you

**Comment by aahmed19** [comment]
Still not working, I cloned MechanicalSoup and ran setup.py. I also tried just installing it directly from github. I'm still running into this issue. I have Python 3.5.2.

**Comment by moy** [comment]
I'm 99.9 % sure you're still using the old version (or perhaps a mix between the old and the new one). Perhaps you have one installed user wide and the other system wide?

**Comment by willcoxDev** [comment]
I am using python 3.6 and installed mechanical soup using the pip, I get this error. How do I use a different version I clicked on the link but no link for 3.6

**Comment by moy** [comment]
Not sure how many times I'll have to repeat this: the released version doesn't contain statefulBrowser. I'll make a release when I get time (might not be so soon :-().
