### ISSUE TITLE
Missing input field when submitting a form

### ISSUE THREAD

**Issue by hypatia1** [hickford/MechanicalSoup#65]
When trying to submit a form that looks like:
```
<form action="/index.php" class="form-class" method="post">
 <input name="__csrf_magic" type="hidden" value="sid:foo"/>
<input id="usernamefld" name="usernamefld" type="text"/>
<input id="passwordfld" name="passwordfld" type="password"/>
<button name="login" type="submit"> Login </button>
</form>
```
My browser posts the following:
```__csrf_magic=sis:foo&usernamefld=user&passwordfld=secret&login=```
MechanicalSoup does not send the "```&login=```" part. Because of this I cannot log into the site with MechanicalSoup.

**Comment by moy** [comment]
Can you post your Python code, or at least tell us what you are using?

**Comment by hypatia1** [comment]
Here is my stripped down source with only the relevant code:
``` #! /usr/bin/env python3

import mechanicalsoup, sys
from requests import Session

URL="https://172.16.32.1/"

session = Session()
session.verify = False

br = mechanicalsoup.Browser(session=session,soup_config={'features':'lxml'})

login_page = br.get(URL)
login_page.raise_for_status()

login_form = login_page.soup.find('form', {'class':'form-horizontal'})
login_form.find(attrs={"id":"usernamefld"})['value']=args.username
login_form.find(attrs={"id":"passwordfld"})['value']=args.password
    
dash_page = br.submit(login_form, URL)   # submitting the login credentials

if 'Username or Password incorrect' in dash_page.soup.get_text():
    sys.stderr.write("\nError: login failed. Check your URL & credentials.\n")
        sys.exit(1)
elif 'System Information' not in dash_page.soup.get_text():
    sys.stderr.write("\nError: login failed. Check your URL & credentials-2.\n")
    sys.exit(1)
else:
    print('I think we are logged in!')
```
The web server always returns me to the login page because missing "login" field in the post.

**Comment by moy** [comment]
MechanicalSoup does not try to guess which submit button you are using (there may be several). It could, especially in cases when there's only one. Patches welcome to improve this (I may work on that myself, but not in the near future).

You can already deal with this:

* If you use `StatefulBrowser` (not in a released version yet), then `submit_selected` has a `bntName` arg exactly for that.

* Otherwise, passing `data={'login' : ''}` to `Browser.submit()` should do the trick.

**Comment by hypatia1** [comment]
Thank you for the advice. That did the trick.
Sorry for opening an issue, when the real bug was my own misunderstanding.

**Comment by dbrobins** [comment]
Passing a btnName didn't help me; I posted a PR to fix choose_submit. #70
