### ISSUE TITLE
Error: mechanicalsoup has no attribute StatefulBrowser

### ISSUE THREAD

**Issue by nehalbhanushali** [hickford/MechanicalSoup#66]
Any pointers?

**Comment by moy** [comment]
Yes : #59 and #60 ;-).

**Comment by ntitty** [comment]
It seems that the whl file at pypi site does not have two files.
stateful_browser.py
utils.py

https://pypi.python.org/pypi/MechanicalSoup/

**Comment by moy** [comment]
Of course, statefulBrowser.py is not in a released version yet.

I'd say,  it's probably why each of the bugs I pointed you to say "from git, not the latest released version yet" ;-).
