### ISSUE TITLE
Make a release with statefulBrowser.py

### ISSUE THREAD

**Issue by moy** [hickford/MechanicalSoup#69]
We're having a lot of users troubled by the fact that statefulBrowser is documented but not released. It's been there for a while now. If anyone has trouble with it, please report bugs ASAP.

We should definitely make a release.

@hickford: can you either do the release, or give me permission on pypi? I'm `moy` there.

**Comment by hickford** [comment]
You're welcome to make a release. I've given you the permissions on PyPI. https://pypi.python.org/pypi/MechanicalSoup/

> Package Index Maintainer: moy

**Comment by moy** [comment]
Released, on GitHub and Pypi. Thanks for giving me access.
