### ISSUE TITLE
Migrate tests to pyunit

### ISSUE THREAD

**Issue by moy** [hickford/MechanicalSoup#73]
Pyunit is a very simple unit tests framework, but could save us a bit of work, e.g.

```Python
    try:
        resp = browser.get("http://httpbin.org/nosuchpage")
    except mechanicalsoup.LinkNotFoundError:
        pass
    else:
        assert False
```

Could be written as stg like

```Python
with self.assertRaises(mechanicalsoup.LinkNotFoundError) as context:
    resp = browser.get("http://httpbin.org/nosuchpage")
```

**Comment by rachmadaniHaryono** [comment]
afaik pytest have also method to test the raised error

https://docs.pytest.org/en/latest/assert.html

```python
with pytest.raises(mechanicalsoup.LinkNotFoundError) as context:
    resp = browser.get("http://httpbin.org/nosuchpage")
````

**Comment by moy** [comment]
Indeed, I knew `pytest` as a launcher but not as an API. Let's stay in the pytest world for both launching and the actual code.
