### ISSUE TITLE
browser = mechanicalsoup.StatefulBrowser(), then can browser access the original soup class?

### ISSUE THREAD

**Issue by entrepreneurss** [hickford/MechanicalSoup#75]
Hi guys, MechanicalSoup is a wonderful wrappers of BeautifulSoup and Mechane, and it's support python3, here I've an issue, can MechanicalSoup access the original BeautifulSoup's functions? Cause I don't see a soup object in the output of dir(browser):

browser = mechanicalsoup.StatefulBrowser()
print(dir(browser))

['_StatefulBrowser__current_form', '_StatefulBrowser__current_page', '_StatefulBrowser__current_url', '_StatefulBrowser__debug', '_StatefulBrowser__verbose', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_build_request', '_prepare_request', 'absolute_url', 'add_soup', 'find_link', 'follow_link', 'get', 'get_current_form', 'get_current_page', 'get_debug', 'get_url', 'launch_browser', 'links', 'list_links', 'new_control', 'open', 'open_relative', 'post', 'request', 'select_custom', 'select_form', 'session', 'set_debug', 'set_verbose', 'soup_config', 'submit', 'submit_selected']

**Comment by moy** [comment]
Isn't `get_current_page()` what you're looking for?

**Comment by moy** [comment]
I'm assuming my reply above answered your question. If not, please reopen.
