### ISSUE TITLE
Ability to customize user agent

### ISSUE THREAD

**Issue by eoghanmurray** [hickford/MechanicalSoup#77]
First thing you do if you are getting different output from a Python script (vs. your Browser) is change the script UA to match your browser to see if the server is sniffing it.  I can submit a patch if you like unless there is an existing way of modifying request headers?

**Comment by moy** [comment]
Would no OK to me, but the documentation should state that this is not good practice: in general the target website likes to have accurate logs by user agent, and a server side user agent detection is in principle done for a good reason (well, in principle...). 

Cheers, 

Le 6 août 2017 23:19:41 GMT+02:00, Eoghan Murray <notifications@github.com> a écrit :
>First thing you do if you are getting different output from a Python
>script (vs. your Browser) is change the script UA to match your browser
>to see if the server is sniffing it.  I can submit a patch if you like?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hickford/MechanicalSoup/issues/77

-- 
Matthieu Moy
http://matthieu-moy.fr/
Envoyé de mon téléphone. Veuillez excuser ma brièveté.

**Comment by moy** [comment]
(Sorry, wrote "would no OK" while I meant "would be OK" in my initial reply, phone keyboard & spellchecker ...)

**Comment by eoghanmurray** [comment]
I also customize user-agent to better identify my script by adding a hyperlink for a webmaster can get more info (rather than just blocking the script/ip address).  E.g. Googlebot uses: `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
Looking at the old mechanize api, it was an ugly property:

    br = mechanize.Browser()
    br.set_handle_robots(False)
    br.addheaders = [('User-agent', 'mysite.example.com')]

I reckon this is not something that should be replicated??

**Comment by moy** [comment]
That sounds like a proper use of user-agent overloading to me indeed. It could be a good example to add to the doc if you add user-agent overloading to MechanicalSoup.

**Comment by eoghanmurray** [comment]
MechanicalSoup currently sets e.g. 'python-requests/2.18.4' as the User Agent.  I wonder if it should send 'MechanicalSoup/0.7.0' as default instead?  I've created https://github.com/hickford/MechanicalSoup/pull/81 as a first step towards this (that pull request should be useful even if you don't agree on a 'MechanicalSoup/0.7.0' as default)

**Comment by moy** [comment]
Perhaps a better default may be `python-requests/2.18.4 (MechanicalSoup/0.7.0)`, so that people who filter according to the start of the string still get `python-requests`, which is the one doing the hard work.

**Comment by eoghanmurray** [comment]
That sounds good

**Comment by eoghanmurray** [comment]
PR: https://github.com/hickford/MechanicalSoup/pull/82

**Comment by moy** [comment]
merged.
