### ISSUE TITLE
Automated test coverage reporting

### ISSUE THREAD

**Issue by hemberger** [hickford/MechanicalSoup#88]
Using `pytest-cov`, we can create a `.coverage` file that can be sent to Coveralls by TravisCI to report on the test coverage. Is this something the maintainers are interested in setting up?

Quick example of what this would entail:
https://ilovesymposia.com/2014/10/15/continuous-integration-in-python-5-report-test-coverage-using-coveralls/

**Comment by moy** [comment]
Good idea indeed.

**Comment by hugovk** [comment]
Good idea! 

I've found Coveralls to be a bit iffy of late on some other projects, so have been using https://codecov.io instead which looks much better.

**Comment by moy** [comment]
Good news: coveralls.io is already active on this repo. It seems @hickford did some experiments a while ago.

Bad news: I did a quick attempt, but all I get is "No data available in table" on coveralls.io. See https://github.com/moy/MechanicalSoup/tree/coveralls-attempt for what I tried. I probably missed something obvious, but ...

**Comment by hugovk** [comment]
You'll need to tell py.test to run with coverage. Have a look at its - - cov and - - cov-report switches.
