### ISSUE TITLE
What does `StatefulBrowser.submit_selected`'s `btnName` argument do?

### ISSUE THREAD

**Issue by hemberger** [hickford/MechanicalSoup#92]
There is no documentation of the `btnName` argument of the `StatefulBrowser.submit_selected` method, and it simply gets forwarded to the `requests.Request` constructor in a data dict (the [documentation](http://docs.python-requests.org/en/master/api/#requests.Request) for this argument in the `requests` module is not very illuminating either).

I have an example form that looks like this:
```html
<form class="standard" method="POST" action="?sn=2e1b94b5">
    <input class="submit" name="action" type="submit" value="View"/>
    <input class="submit" name="action" type="submit" value="Save"/>
    <input type="checkbox" value="on" name="id[788441]"/>
    <input type="checkbox" value="on" name="id[788558]"/>
</form>
```

Thinking `btnName` meant "button name" (as in, the value of the submit element to be clicked), I tried the following code:
```python
def SelectCheckboxes(br, names, submit_value):
  br.select_form('form')
  br.get_current_form().check({name: "on" for name in names})
  br.submit_selected(btnName=submit_value)

SelectCheckboxes(br, ['id[788441]'], "View")
```

The above code submits using the "Save" element instead of "View". Unsurprisingly, the code works correctly with the following change to `SelectCheckboxes`:
```diff
-  br.submit_selected(btnName=submit_value)
+  br.get_current_form().choose_submit(submit_value)
+  br.submit_selected()
```
But the existence of the `choose_submit` method further disguises what `btnName` is actually supposed to be. Any clarification would be greatly appreciated!

**Comment by hemberger** [comment]
Upon further investigation, there are three problems here:
1. There is a bug in the return value of `Form.choose_submit` where it was returning `True` when it hadn't found the specified element.

2. `Form.choose_submit` only has the ability to select input element _names_, not input element _values_. Because the return value was incorrect (problem 1), I didn't notice this was happening. Note: `mechanize` can select input elements by name using the `label` argument (i.e. `br.submit(label=submit_value)`), so perhaps it can be added as a feature here.

3. `Browser.prepare_request` does not respect the `btnName` argument passed by `StatefulBrowser.submit_selected` when there are multiple submit inputs/buttons. Let me describe what happens step by step. First, `StatefulBrowser.submit_selected` [passes](https://github.com/hickford/MechanicalSoup/blob/a4b5988ccc2636dee8fcc8f333a3b4ca9d6862ca/mechanicalsoup/stateful_browser.py#L117) `data={btnName: ''}` to (ultimately) `Browser.prepare_request`. However, as `Browser.prepare_request` [loops over the input elements](https://github.com/hickford/MechanicalSoup/blob/a4b5988ccc2636dee8fcc8f333a3b4ca9d6862ca/mechanicalsoup/browser.py#L91) (_which includes the submit inputs_), it [indiscriminately adds all input elements to the data dict](https://github.com/hickford/MechanicalSoup/blob/a4b5988ccc2636dee8fcc8f333a3b4ca9d6862ca/mechanicalsoup/browser.py#L117) of the POST request, including the submit inputs that were not specified. If the inputs have the same name attribute, then the last one will be submitted; if the name attributes are different, then they will all be submitted and you will likely get undefined behavior from the website (depending on how they handle the POST data). Neither result is correct.

I will provide a PR to address these problems shortly.

**Comment by moy** [comment]
`btnName` is not tested within MechanicalSoup, but I use it in chamilotools: 
https://gitlab.com/chamilotools/chamilotools/blob/master/chamilolib/create_quiz_lib.py#L304
https://gitlab.com/chamilotools/chamilotools/blob/master/chamilolib/documents.py#L68
https://gitlab.com/chamilotools/chamilotools/blob/master/chamilolib/intro.py#L69
Unfortunately, I don't remember exactly what/how I did it. But I'm 99% sure I added btnName for a reason and at least one of the instances above correspond to a case where not using btnName did not work. Doesn't mean it's not buggy, but there should be one instance where it does work ;-).

It probably makes sense to deprecate `btnName` in favor of `choose_submit`, but unfortunately we can't remove it completely because it has one user.
