### ISSUE TITLE
Update PyPI version

### ISSUE THREAD

**Issue by hemberger** [hickford/MechanicalSoup#93]
There have been a number of useful changes since v0.7.0. I was wondering what would need to be done to have a new tagged release so that the latest version in PyPI can be updated. Thanks!

**Comment by moy** [comment]
Indeed, the changes deserve a release. I should be able to tag a release soon.

**Comment by ztane** [comment]
Damn, I installed from PyPI as per readme on github, and it didn't work :D

**Comment by moy** [comment]
https://pypi.python.org/pypi?:action=display&name=MechanicalSoup&version=0.8.0
